apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-normal
  labels:
    app: nginx-normal
spec:
  selector:
    matchLabels:
      app: nginx-normal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-normal
    spec:
      containers:
      - image:  nginx:alpine
        name: nginx-normal
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  5000
          name: nginx-normal
        volumeMounts:
        - mountPath: /data
          name: config-file
      volumes:
        - name: config-file
          configMap: 
            name: common-config